const data_detail_pesanan_multi_produk_all_status = {
  order_detail: {
    id: 1,
    created_at: '2018-08-14 04:23:30',
    updated_at: '2018-08-14 04:48:11',
    deleted_at: null,
    order_number: '11808141',
    real_invoice: 'NO',
    vip: '0',
    payment_type: '',
    refcode: '',
    customer_id: 1,
    owner: 3,
    website: 1,
    unique_code: 238,
    status: 'approved',
    tax_type: '',
    tax_result: 0,
    verify: 0,
    total: 600238,
    cashback: 0,
    inquiry_id: 1,
    payment_status: 'unpaid',
    payment_duedate: null,
    payment_notes: '',
    invoice_address: 'no',
    invoice_receipt: '',
    moota_stat: '',
    payment_revision: '',
    approve_logs: 'null',
    tax_invoice: '',
    receipt: '',
    tele_created: 0,
    service_fee: 0,
    meta: null,
    referto: null,
    auto_cancel: null,
    last_fu_ar_date: null,
    app: null,
    tx_id: null,
    voucher_amount: null,
    voucher_id: null,
  },
  customer_info: {
    id: 1,
    created_at: '2018-08-14 04:23:30',
    updated_at: '2018-08-14 04:31:06',
    deleted_at: null,
    order_id: 1,
    type: 0,
    email: 'muza@prestisa.com',
    phone: '087883486743',
    name: 'Muza',
    company_type: null,
    company_name: null,
    company_address: null,
    company_email: null,
    company_phone: null,
    no_finance: null,
    no_finance_2: null,
    logs: null,
  },
  list_item: [
    {
      id: 3,
      assignment: 3,
      created_at: '2018-08-14 04:31:06',
      updated_at: '2018-08-14 07:50:49',
      deleted_at: null,
      order_id: 1,
      product_id: 2,
      name: 'Bunga Papan Merah C9-03',
      price: 600000,
      capital_price: 400000,
      qty: 1,
      bought: 1,
      image: '/assets/images/products/BPDC-1.png',
      product_code: 'BPDC-1',
      subtotal: 600000,
      shipping_cost: 10000,
      shipping_expedition: '',
      shipping_address:
        'Jalan Parangtritis Gang Rama No. 1090, Danunegaran, Mantrijeron, 55143',
      sender_name: 'PT. Muzaaa muszzzzzaaaa muzzzzzzaaaaa',
      greetings: 'Selamat dan Sukses \nSania & Elon \nSemoga Bahagia Selalu',
      receiver_name: 'muza',
      receiver_phone: '085225777888',
      notes: 'Bunganya tolong jangan sampai rusak ketika sampai',
      notes_internal: '',
      occasion: '',
      city: 1642909,
      country: 1643084,
      province: 1642907,
      date_time: '2018-08-14 15:25:18',
      checked: '',
      problem: 0,
      fu_er: null,
      //
      // data_yang_belum_ada
      city_name: 'Yogyakarta',
      order_status: 'menunggu pembayaran', //menunggu, selasai (sesuai JIRA)
      status_id: 2,
      arrived_image: '',
      complain_id: '',
    },
    {
      id: 3,
      assignment: 3,
      created_at: '2018-08-14 04:31:06',
      updated_at: '2018-08-14 07:50:49',
      deleted_at: null,
      order_id: 1,
      product_id: 2,
      name: 'Yellow Bouquet - 01',
      price: 600000,
      capital_price: 400000,
      qty: 1,
      bought: 1,
      image: '/assets/images/products/BPDC-1.png',
      product_code: 'BPDC-1',
      subtotal: 600000,
      shipping_cost: 10000,
      shipping_expedition: '',
      shipping_address:
        'Jalan Parangtritis Gang Rama No. 1090, Danunegaran, Mantrijeron, 55143',
      sender_name: 'PT. Muzaaa muszzzzzaaaa muzzzzzzaaaaa',
      greetings: 'Selamat dan Sukses \nSania & Elon \nSemoga Bahagia Selalu',
      receiver_name: 'muza',
      receiver_phone: '085225777888',
      notes: 'Bunganya tolong jangan sampai rusak ketika sampai',
      notes_internal: '',
      occasion: '',
      city: 1642909,
      country: 1643084,
      province: 1642907,
      date_time: '2018-08-14 15:25:18',
      checked: '',
      problem: 0,
      fu_er: null,
      //
      // data_yang_belum_ada
      city_name: 'Yogyakarta',
      order_status: 'menunggu konfirmasi', //menunggu, selasai (sesuai JIRA)
      status_id: 4,
      arrived_image: '',
      complain_id: '',
    },
    {
      id: 3,
      assignment: 3,
      created_at: '2018-08-14 04:31:06',
      updated_at: '2018-08-14 07:50:49',
      deleted_at: null,
      order_id: 1,
      product_id: 2,
      name: 'Bunga Papan Kuning CY-03',
      price: 600000,
      capital_price: 400000,
      qty: 1,
      bought: 1,
      image: '/assets/images/products/BPDC-1.png',
      product_code: 'BPDC-1',
      subtotal: 600000,
      shipping_cost: 10000,
      shipping_expedition: '',
      shipping_address:
        'Jalan Parangtritis Gang Rama No. 1090, Danunegaran, Mantrijeron, 55143',
      sender_name: 'PT. Muzaaa muszzzzzaaaa muzzzzzzaaaaa',
      greetings: 'Selamat dan Sukses \nSania & Elon \nSemoga Bahagia Selalu',
      receiver_name: 'muza',
      receiver_phone: '085225777888',
      notes: 'Bunganya tolong jangan sampai rusak ketika sampai',
      notes_internal: '',
      occasion: '',
      city: 1642909,
      country: 1643084,
      province: 1642907,
      date_time: '2018-08-14 15:25:18',
      checked: '',
      problem: 0,
      fu_er: null,
      //
      // data_yang_belum_ada
      city_name: 'Yogyakarta',
      order_status: 'dirangkai', //menunggu, selasai (sesuai JIRA)
      status_id: 5,
      arrived_image: '',
      complain_id: '',
    },

    {
      id: 3,
      assignment: 3,
      created_at: '2018-08-14 04:31:06',
      updated_at: '2018-08-14 07:50:49',
      deleted_at: null,
      order_id: 1,
      product_id: 2,
      name: 'Bunga Papan Kuning CY-03',
      price: 600000,
      capital_price: 400000,
      qty: 1,
      bought: 1,
      image: '/assets/images/products/BPDC-1.png',
      product_code: 'BPDC-1',
      subtotal: 600000,
      shipping_cost: 10000,
      shipping_expedition: '',
      shipping_address:
        'Jalan Parangtritis Gang Rama No. 1090, Danunegaran, Mantrijeron, 55143',
      sender_name: 'PT. Muzaaa muszzzzzaaaa muzzzzzzaaaaa',
      greetings: 'Selamat dan Sukses \nSania & Elon \nSemoga Bahagia Selalu',
      receiver_name: 'muza',
      receiver_phone: '085225777888',
      notes: 'Bunganya tolong jangan sampai rusak ketika sampai',
      notes_internal: '',
      occasion: '',
      city: 1642909,
      country: 1643084,
      province: 1642907,
      date_time: '2018-08-14 15:25:18',
      checked: '',
      problem: 0,
      fu_er: null,
      //
      // data_yang_belum_ada
      city_name: 'Yogyakarta',
      order_status: 'preview produk', //menunggu, selasai (sesuai JIRA)
      status_id: 6,
      arrived_image: '',
      complain_id: '',
    },
    {
      id: 3,
      assignment: 3,
      created_at: '2018-08-14 04:31:06',
      updated_at: '2018-08-14 07:50:49',
      deleted_at: null,
      order_id: 1,
      product_id: 2,
      name: 'Bunga Papan Kuning CY-03',
      price: 600000,
      capital_price: 400000,
      qty: 1,
      bought: 1,
      image: '/assets/images/products/BPDC-1.png',
      product_code: 'BPDC-1',
      subtotal: 600000,
      shipping_cost: 10000,
      shipping_expedition: '',
      shipping_address:
        'Jalan Parangtritis Gang Rama No. 1090, Danunegaran, Mantrijeron, 55143',
      sender_name: 'PT. Muzaaa muszzzzzaaaa muzzzzzzaaaaa',
      greetings: 'Selamat dan Sukses \nSania & Elon \nSemoga Bahagia Selalu',
      receiver_name: 'muza',
      receiver_phone: '085225777888',
      notes: 'Bunganya tolong jangan sampai rusak ketika sampai',
      notes_internal: '',
      occasion: '',
      city: 1642909,
      country: 1643084,
      province: 1642907,
      date_time: '2018-08-14 15:25:18',
      checked: '',
      problem: 0,
      fu_er: null,
      //
      // data_yang_belum_ada
      city_name: 'Yogyakarta',
      order_status: 'revisi produk', //menunggu, selasai (sesuai JIRA)
      status_id: 7,
      arrived_image: '',
      complain_id: '',
    },
    {
      id: 3,
      assignment: 3,
      created_at: '2018-08-14 04:31:06',
      updated_at: '2018-08-14 07:50:49',
      deleted_at: null,
      order_id: 1,
      product_id: 2,
      name: 'Bunga Papan Kuning CY-03',
      price: 600000,
      capital_price: 400000,
      qty: 1,
      bought: 1,
      image: '/assets/images/products/BPDC-1.png',
      product_code: 'BPDC-1',
      subtotal: 600000,
      shipping_cost: 10000,
      shipping_expedition: '',
      shipping_address:
        'Jalan Parangtritis Gang Rama No. 1090, Danunegaran, Mantrijeron, 55143',
      sender_name: 'PT. Muzaaa muszzzzzaaaa muzzzzzzaaaaa',
      greetings: 'Selamat dan Sukses \nSania & Elon \nSemoga Bahagia Selalu',
      receiver_name: 'muza',
      receiver_phone: '085225777888',
      notes: 'Bunganya tolong jangan sampai rusak ketika sampai',
      notes_internal: '',
      occasion: '',
      city: 1642909,
      country: 1643084,
      province: 1642907,
      date_time: '2018-08-14 15:25:18',
      checked: '',
      problem: 0,
      fu_er: null,
      //
      // data_yang_belum_ada
      city_name: 'Yogyakarta',
      order_status: 'dalam perjalanan', //menunggu, selasai (sesuai JIRA)
      status_id: 9,
      arrived_image: '',
      complain_id: '',
    },
    {
      id: 3,
      assignment: 3,
      created_at: '2018-08-14 04:31:06',
      updated_at: '2018-08-14 07:50:49',
      deleted_at: null,
      order_id: 1,
      product_id: 2,
      name: 'Bunga Papan Kuning CY-03',
      price: 600000,
      capital_price: 400000,
      qty: 1,
      bought: 1,
      image: '/assets/images/products/BPDC-1.png',
      product_code: 'BPDC-1',
      subtotal: 600000,
      shipping_cost: 10000,
      shipping_expedition: '',
      shipping_address:
        'Jalan Parangtritis Gang Rama No. 1090, Danunegaran, Mantrijeron, 55143',
      sender_name: 'PT. Muzaaa muszzzzzaaaa muzzzzzzaaaaa',
      greetings: 'Selamat dan Sukses \nSania & Elon \nSemoga Bahagia Selalu',
      receiver_name: 'muza',
      receiver_phone: '085225777888',
      notes: 'Bunganya tolong jangan sampai rusak ketika sampai',
      notes_internal: '',
      occasion: '',
      city: 1642909,
      country: 1643084,
      province: 1642907,
      date_time: '2018-08-14 15:25:18',
      checked: '',
      problem: 0,
      fu_er: null,
      //
      // data_yang_belum_ada
      city_name: 'Yogyakarta',
      order_status: 'pesanan tiba', //menunggu, selasai (sesuai JIRA)
      status_id: 10,
      arrived_image:
        'https://images.unsplash.com/photo-1525310072745-f49212b5ac6d',
      arrived_image_name: 'photo-1525310072745-f49212b5ac6d',
      complain_id: '',
    },

    {
      id: 3,
      assignment: 3,
      created_at: '2018-08-14 04:31:06',
      updated_at: '2018-08-14 07:50:49',
      deleted_at: null,
      order_id: 1,
      product_id: 2,
      name: 'Bunga Papan Kuning CY-03',
      price: 600000,
      capital_price: 400000,
      qty: 1,
      bought: 1,
      image: '/assets/images/products/BPDC-1.png',
      product_code: 'BPDC-1',
      subtotal: 600000,
      shipping_cost: 10000,
      shipping_expedition: '',
      shipping_address:
        'Jalan Parangtritis Gang Rama No. 1090, Danunegaran, Mantrijeron, 55143',
      sender_name: 'PT. Muzaaa muszzzzzaaaa muzzzzzzaaaaa',
      greetings: 'Selamat dan Sukses \nSania & Elon \nSemoga Bahagia Selalu',
      receiver_name: 'muza',
      receiver_phone: '085225777888',
      notes: 'Bunganya tolong jangan sampai rusak ketika sampai',
      notes_internal: '',
      occasion: '',
      city: 1642909,
      country: 1643084,
      province: 1642907,
      date_time: '2018-08-14 15:25:18',
      checked: '',
      problem: 0,
      fu_er: null,
      //
      // data_yang_belum_ada
      city_name: 'Yogyakarta',
      order_status: 'komplain diajukan', //menunggu, selasai (sesuai JIRA)
      status_id: 12,
      arrived_image: '',
      complain_id: '',
    },
    {
      id: 3,
      assignment: 3,
      created_at: '2018-08-14 04:31:06',
      updated_at: '2018-08-14 07:50:49',
      deleted_at: null,
      order_id: 1,
      product_id: 2,
      name: 'Bunga Papan Kuning CY-03',
      price: 600000,
      capital_price: 400000,
      qty: 1,
      bought: 1,
      image: '/assets/images/products/BPDC-1.png',
      product_code: 'BPDC-1',
      subtotal: 600000,
      shipping_cost: 10000,
      shipping_expedition: '',
      shipping_address:
        'Jalan Parangtritis Gang Rama No. 1090, Danunegaran, Mantrijeron, 55143',
      sender_name: 'PT. Muzaaa muszzzzzaaaa muzzzzzzaaaaa',
      greetings: 'Selamat dan Sukses \nSania & Elon \nSemoga Bahagia Selalu',
      receiver_name: 'muza',
      receiver_phone: '085225777888',
      notes: 'Bunganya tolong jangan sampai rusak ketika sampai',
      notes_internal: '',
      occasion: '',
      city: 1642909,
      country: 1643084,
      province: 1642907,
      date_time: '2018-08-14 15:25:18',
      checked: '',
      problem: 0,
      fu_er: null,
      //
      // data_yang_belum_ada
      city_name: 'Yogyakarta',
      order_status: 'komplain diproses', //menunggu, selasai (sesuai JIRA)
      status_id: 13,
      arrived_image: '',
      complain_id: '',
    },
    {
      id: 3,
      assignment: 3,
      created_at: '2018-08-14 04:31:06',
      updated_at: '2018-08-14 07:50:49',
      deleted_at: null,
      order_id: 1,
      product_id: 2,
      name: 'Bunga Papan Kuning CY-03',
      price: 600000,
      capital_price: 400000,
      qty: 1,
      bought: 1,
      image: '/assets/images/products/BPDC-1.png',
      product_code: 'BPDC-1',
      subtotal: 600000,
      shipping_cost: 10000,
      shipping_expedition: '',
      shipping_address:
        'Jalan Parangtritis Gang Rama No. 1090, Danunegaran, Mantrijeron, 55143',
      sender_name: 'PT. Muzaaa muszzzzzaaaa muzzzzzzaaaaa',
      greetings: 'Selamat dan Sukses \nSania & Elon \nSemoga Bahagia Selalu',
      receiver_name: 'muza',
      receiver_phone: '085225777888',
      notes: 'Bunganya tolong jangan sampai rusak ketika sampai',
      notes_internal: '',
      occasion: '',
      city: 1642909,
      country: 1643084,
      province: 1642907,
      date_time: '2018-08-14 15:25:18',
      checked: '',
      problem: 0,
      fu_er: null,
      //
      // data_yang_belum_ada
      city_name: 'Yogyakarta',
      order_status: 'komplain terselesaikan', //menunggu, selasai (sesuai JIRA)
      status_id: 14,
      arrived_image: '',
      complain_id: '',
    },
    {
      id: 3,
      assignment: 3,
      created_at: '2018-08-14 04:31:06',
      updated_at: '2018-08-14 07:50:49',
      deleted_at: null,
      order_id: 1,
      product_id: 2,
      name: 'Bunga Papan Kuning CY-03',
      price: 600000,
      capital_price: 400000,
      qty: 1,
      bought: 1,
      image: '/assets/images/products/BPDC-1.png',
      product_code: 'BPDC-1',
      subtotal: 600000,
      shipping_cost: 10000,
      shipping_expedition: '',
      shipping_address:
        'Jalan Parangtritis Gang Rama No. 1090, Danunegaran, Mantrijeron, 55143',
      sender_name: 'PT. Muzaaa muszzzzzaaaa muzzzzzzaaaaa',
      greetings: 'Selamat dan Sukses \nSania & Elon \nSemoga Bahagia Selalu',
      receiver_name: 'muza',
      receiver_phone: '085225777888',
      notes: 'Bunganya tolong jangan sampai rusak ketika sampai',
      notes_internal: '',
      occasion: '',
      city: 1642909,
      country: 1643084,
      province: 1642907,
      date_time: '2018-08-14 15:25:18',
      checked: '',
      problem: 0,
      fu_er: null,
      //
      // data_yang_belum_ada
      city_name: 'Yogyakarta',
      order_status: 'selesai', //menunggu, selasai (sesuai JIRA)
      status_id: 16,
      arrived_image: '',
      complain_id: '',
    },
    {
      id: 3,
      assignment: 3,
      created_at: '2018-08-14 04:31:06',
      updated_at: '2018-08-14 07:50:49',
      deleted_at: null,
      order_id: 1,
      product_id: 2,
      name: 'Bunga Papan Kuning CY-03',
      price: 600000,
      capital_price: 400000,
      qty: 1,
      bought: 1,
      image: '/assets/images/products/BPDC-1.png',
      product_code: 'BPDC-1',
      subtotal: 600000,
      shipping_cost: 10000,
      shipping_expedition: '',
      shipping_address:
        'Jalan Parangtritis Gang Rama No. 1090, Danunegaran, Mantrijeron, 55143',
      sender_name: 'PT. Muzaaa muszzzzzaaaa muzzzzzzaaaaa',
      greetings: 'Selamat dan Sukses \nSania & Elon \nSemoga Bahagia Selalu',
      receiver_name: 'muza',
      receiver_phone: '085225777888',
      notes: 'Bunganya tolong jangan sampai rusak ketika sampai',
      notes_internal: '',
      occasion: '',
      city: 1642909,
      country: 1643084,
      province: 1642907,
      date_time: '2018-08-14 15:25:18',
      checked: '',
      problem: 0,
      fu_er: null,
      //
      // data_yang_belum_ada
      city_name: 'Yogyakarta',
      order_status: 'dibatalkan', //menunggu, selasai (sesuai JIRA)
      status_id: 18,
      arrived_image: '',
      complain_id: '',
    },
    {
      id: 3,
      assignment: 3,
      created_at: '2018-08-14 04:31:06',
      updated_at: '2018-08-14 07:50:49',
      deleted_at: null,
      order_id: 1,
      product_id: 2,
      name: 'Bunga Papan Kuning CY-03',
      price: 600000,
      capital_price: 400000,
      qty: 1,
      bought: 1,
      image: '/assets/images/products/BPDC-1.png',
      product_code: 'BPDC-1',
      subtotal: 600000,
      shipping_cost: 10000,
      shipping_expedition: '',
      shipping_address:
        'Jalan Parangtritis Gang Rama No. 1090, Danunegaran, Mantrijeron, 55143',
      sender_name: 'PT. Muzaaa muszzzzzaaaa muzzzzzzaaaaa',
      greetings: 'Selamat dan Sukses \nSania & Elon \nSemoga Bahagia Selalu',
      receiver_name: 'muza',
      receiver_phone: '085225777888',
      notes: 'Bunganya tolong jangan sampai rusak ketika sampai',
      notes_internal: '',
      occasion: '',
      city: 1642909,
      country: 1643084,
      province: 1642907,
      date_time: '2018-08-14 15:25:18',
      checked: '',
      problem: 0,
      fu_er: null,
      //
      // data_yang_belum_ada
      city_name: 'Yogyakarta',
      order_status: 'pembayaran gagal', //menunggu, selasai (sesuai JIRA)
      status_id: 19,
      arrived_image: '',
      complain_id: '',
    },
  ],
  cashback: 9999999,
  total_cost: {
    subtotal: 1358000,
    shipping_cost: 30000,
    discount: 10000,
    total: 1378000,
  },
  payment_method: {
    name: 'mandiri virtual account',
    total: 1378000,
  },
}
const data_detail_pesanan_single = {
  order_detail: {
    id: 1,
    created_at: '2018-08-14 04:23:30',
    updated_at: '2018-08-14 04:48:11',
    deleted_at: null,
    order_number: '11808141',
    real_invoice: 'NO',
    vip: '0',
    payment_type: '',
    refcode: '',
    customer_id: 1,
    owner: 3,
    website: 1,
    unique_code: 238,
    status: 'approved',
    tax_type: '',
    tax_result: 0,
    verify: 0,
    total: 600238,
    cashback: 0,
    inquiry_id: 1,
    payment_status: 'unpaid',
    payment_duedate: null,
    payment_notes: '',
    invoice_address: 'no',
    invoice_receipt: '',
    moota_stat: '',
    payment_revision: '',
    approve_logs: 'null',
    tax_invoice: '',
    receipt: '',
    tele_created: 0,
    service_fee: 0,
    meta: null,
    referto: null,
    auto_cancel: null,
    last_fu_ar_date: null,
    app: null,
    tx_id: null,
    voucher_amount: null,
    voucher_id: null,
  },
  customer_info: {
    id: 1,
    created_at: '2018-08-14 04:23:30',
    updated_at: '2018-08-14 04:31:06',
    deleted_at: null,
    order_id: 1,
    type: 0,
    email: 'muza@prestisa.com',
    phone: '087883486743',
    name: 'Muza',
    company_type: null,
    company_name: null,
    company_address: null,
    company_email: null,
    company_phone: null,
    no_finance: null,
    no_finance_2: null,
    logs: null,
  },
  list_item: [
    {
      id: 3,
      assignment: 3,
      created_at: '2018-08-14 04:31:06',
      updated_at: '2018-08-14 07:50:49',
      deleted_at: null,
      order_id: 1,
      product_id: 2,
      name: 'Bunga Papan Merah C9-03',
      price: 600000,
      capital_price: 400000,
      qty: 1,
      bought: 1,
      image: '/assets/images/products/BPDC-1.png',
      product_code: 'BPDC-1',
      subtotal: 600000,
      shipping_cost: 10000,
      shipping_expedition: '',
      shipping_address:
        'Jalan Parangtritis Gang Rama No. 1090, Danunegaran, Mantrijeron, 55143',
      sender_name: 'PT. Muzaaa muszzzzzaaaa muzzzzzzaaaaa',
      greetings: 'Selamat dan Sukses \nSania & Elon \nSemoga Bahagia Selalu',
      receiver_name: 'muza',
      receiver_phone: '085225777888',
      notes: 'Bunganya tolong jangan sampai rusak ketika sampai',
      notes_internal: '',
      occasion: '',
      city: 1642909,
      country: 1643084,
      province: 1642907,
      date_time: '2018-08-14 15:25:18',
      checked: '',
      problem: 0,
      fu_er: null,
      //
      // data_yang_belum_ada
      city_name: 'Yogyakarta',
      order_status: 'menunggu pembayaran', //menunggu, selasai (sesuai JIRA)
      status_id: 2,
      arrived_image: '',
      complain_id: '',
    },
  ],
  cashback: '',
  total_cost: {
    subtotal: 1358000,
    shipping_cost: 30000,
    discount: 10000,
    total: 1378000,
  },
  payment_method: {
    name: 'mandiri virtual account',
    total: 1378000,
  },
}

export {
  data_detail_pesanan_multi_produk_all_status,
  data_detail_pesanan_single,
}
