export const data_redeem_voucher = [
  {
    id: 1,
    type: 'ovo',
    name: 'OVO',
    icon: 'https://play-lh.googleusercontent.com/yNGcOowg9DNn4YTEaeOT7Q99-5PCM2F0pnlxFDlZ-tngTV_IS-eq_R1AbQkYNTrC3_o=s128-rw',
    child: [
      {
        id: 111,
        parent_id: 1,
        cat: 'ovo',
        cat_name: 'OVO',
        name: 'Voucher Saldo OVO',
        ammounts: 25000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 25000,
      },
      {
        id: 112,
        parent_id: 1,
        cat: 'ovo',
        cat_name: 'OVO',
        name: 'Voucher Saldo OVO',
        ammounts: 5000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 5000,
      },
      {
        id: 113,
        parent_id: 1,
        cat: 'ovo',
        cat_name: 'OVO',
        name: 'Voucher Saldo OVO',
        ammounts: 105000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 105000,
      },
      {
        id: 114,
        parent_id: 1,
        cat: 'ovo',
        cat_name: 'OVO',
        name: 'Voucher Saldo OVO',
        ammounts: 200000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 200000,
      },
      {
        id: 114,
        parent_id: 1,
        cat: 'ovo',
        cat_name: 'OVO',
        name: 'Voucher Saldo OVO',
        ammounts: 200000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 200000,
      },
      {
        id: 111,
        parent_id: 1,
        cat: 'ovo',
        cat_name: 'OVO',
        name: 'Voucher Saldo OVO',
        ammounts: 25000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 25000,
      },
      {
        id: 112,
        parent_id: 1,
        cat: 'ovo',
        cat_name: 'OVO',
        name: 'Voucher Saldo OVO',
        ammounts: 5000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 5000,
      },
      {
        id: 113,
        parent_id: 1,
        cat: 'ovo',
        cat_name: 'OVO',
        name: 'Voucher Saldo OVO',
        ammounts: 105000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 105000,
      },
      {
        id: 114,
        parent_id: 1,
        cat: 'ovo',
        cat_name: 'OVO',
        name: 'Voucher Saldo OVO',
        ammounts: 200000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 200000,
      },
      {
        id: 114,
        parent_id: 1,
        cat: 'ovo',
        cat_name: 'OVO',
        name: 'Voucher Saldo OVO',
        ammounts: 200000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 200000,
      },
    ],
  },
  {
    id: 2,
    type: 'gopay',
    name: 'GoPay',
    icon: 'https://gopay.co.id/favicon.png',
    child: [
      {
        id: 211,
        parent_id: 2,
        cat: 'gopay',
        cat_name: 'GoPay',
        name: 'Voucher Saldo GoPay',
        ammounts: 25000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 25000,
      },
      {
        id: 212,
        parent_id: 2,
        cat: 'gopay',
        cat_name: 'GoPay',
        name: 'Voucher Saldo GoPay',
        ammounts: 5000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 5000,
      },
      {
        id: 213,
        parent_id: 2,
        cat: 'gopay',
        cat_name: 'GoPay',
        name: 'Voucher Saldo GoPay',
        ammounts: 105000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 105000,
      },
      {
        id: 214,
        parent_id: 2,
        cat: 'gopay',
        cat_name: 'GoPay',
        name: 'Voucher Saldo GoPay',
        ammounts: 200000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 200000,
      },
      {
        id: 214,
        parent_id: 2,
        cat: 'gopay',
        cat_name: 'GoPay',
        name: 'Voucher Saldo GoPay',
        ammounts: 200000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 200000,
      },
      {
        id: 211,
        parent_id: 2,
        cat: 'gopay',
        cat_name: 'GoPay',
        name: 'Voucher Saldo GoPay',
        ammounts: 25000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 25000,
      },
      {
        id: 212,
        parent_id: 2,
        cat: 'gopay',
        cat_name: 'GoPay',
        name: 'Voucher Saldo GoPay',
        ammounts: 5000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 5000,
      },
      {
        id: 213,
        parent_id: 2,
        cat: 'gopay',
        cat_name: 'GoPay',
        name: 'Voucher Saldo GoPay',
        ammounts: 105000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 105000,
      },
      {
        id: 214,
        parent_id: 2,
        cat: 'gopay',
        cat_name: 'GoPay',
        name: 'Voucher Saldo GoPay',
        ammounts: 200000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 200000,
      },
      {
        id: 214,
        parent_id: 2,
        cat: 'gopay',
        cat_name: 'GoPay',
        name: 'Voucher Saldo GoPay',
        ammounts: 200000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 200000,
      },
    ],
  },
  {
    id: 3,
    type: 'shopeepay',
    name: 'Shopee Pay',
    icon: 'https://shopeepay.co.id/src/pages/home/assets/images/wallet_icon.jpg',
    child: [
      {
        id: 311,
        parent_id: 3,
        cat: 'shopeepay',
        cat_name: 'ShopeePay',
        name: 'Voucher Saldo Shopee Pay',
        ammounts: 25000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 25000,
      },
      {
        id: 312,
        parent_id: 3,
        cat: 'shopeepay',
        cat_name: 'ShopeePay',
        name: 'Voucher Saldo Shopee Pay',
        ammounts: 5000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 5000,
      },
      {
        id: 313,
        parent_id: 3,
        cat: 'shopeepay',
        cat_name: 'ShopeePay',
        name: 'Voucher Saldo Shopee Pay',
        ammounts: 105000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 105000,
      },
      {
        id: 314,
        parent_id: 3,
        cat: 'shopeepay',
        cat_name: 'ShopeePay',
        name: 'Voucher Saldo Shopee Pay',
        ammounts: 200000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 200000,
      },
      {
        id: 314,
        parent_id: 3,
        cat: 'shopeepay',
        cat_name: 'ShopeePay',
        name: 'Voucher Saldo Shopee Pay',
        ammounts: 200000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 200000,
      },
      {
        id: 314,
        parent_id: 3,
        cat: 'shopeepay',
        cat_name: 'ShopeePay',
        name: 'Voucher Saldo Shopee Pay',
        ammounts: 200000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 200000,
      },
      {
        id: 314,
        parent_id: 3,
        cat: 'shopeepay',
        cat_name: 'ShopeePay',
        name: 'Voucher Saldo Shopee Pay',
        ammounts: 200000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 200000,
      },
      {
        id: 314,
        parent_id: 3,
        cat: 'shopeepay',
        cat_name: 'ShopeePay',
        name: 'Voucher Saldo Shopee Pay',
        ammounts: 200000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 200000,
      },
      {
        id: 314,
        parent_id: 3,
        cat: 'shopeepay',
        cat_name: 'ShopeePay',
        name: 'Voucher Saldo Shopee Pay',
        ammounts: 200000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 200000,
      },
      {
        id: 314,
        parent_id: 3,
        cat: 'shopeepay',
        cat_name: 'ShopeePay',
        name: 'Voucher Saldo Shopee Pay',
        ammounts: 200000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 200000,
      },
    ],
  },
  {
    id: 4,
    type: 'tokenlistrik',
    name: 'Token Listrik',
    icon: '',
    child: [
      {
        id: 411,
        parent_id: 4,
        cat: 'tokenlistrik',
        name: 'Voucher Saldo Token Listrik',
        ammounts: 25000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 25000,
      },
      {
        id: 412,
        parent_id: 4,
        cat: 'tokenlistrik',
        name: 'Voucher Saldo Token Listrik',
        ammounts: 5000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 5000,
      },
      {
        id: 413,
        parent_id: 4,
        cat: 'tokenlistrik',
        name: 'Voucher Saldo Token Listrik',
        ammounts: 105000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 105000,
      },
      {
        id: 414,
        parent_id: 4,
        cat: 'tokenlistrik',
        name: 'Voucher Saldo Token Listrik',
        ammounts: 200000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 200000,
      },
      {
        id: 414,
        parent_id: 4,
        cat: 'tokenlistrik',
        name: 'Voucher Saldo Token Listrik',
        ammounts: 200000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 200000,
      },
      {
        id: 414,
        parent_id: 4,
        cat: 'tokenlistrik',
        name: 'Voucher Saldo Token Listrik',
        ammounts: 200000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 200000,
      },
      {
        id: 414,
        parent_id: 4,
        cat: 'tokenlistrik',
        name: 'Voucher Saldo Token Listrik',
        ammounts: 200000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 200000,
      },
      {
        id: 414,
        parent_id: 4,
        cat: 'tokenlistrik',
        name: 'Voucher Saldo Token Listrik',
        ammounts: 200000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 200000,
      },
      {
        id: 414,
        parent_id: 4,
        cat: 'tokenlistrik',
        name: 'Voucher Saldo Token Listrik',
        ammounts: 200000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 200000,
      },
      {
        id: 414,
        parent_id: 4,
        cat: 'tokenlistrik',
        name: 'Voucher Saldo Token Listrik',
        ammounts: 200000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 200000,
      },
    ],
  },
  {
    id: 5,
    type: 'digitalshoping',
    name: 'Belanja Digital',
    icon: '',
    child: [
      {
        id: 511,
        parent_id: 5,
        sub_type_name: 'indomaret',
        sub_type: 6,
        cat: 'digitalshoping',
        name: 'Voucher Saldo Indomaret',
        ammounts: 25000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 25000,
      },
      {
        id: 512,
        parent_id: 5,
        sub_type_name: 'alfamart',
        sub_type: 7,
        cat: 'digitalshoping',
        name: 'Voucher Saldo Alfamart',
        ammounts: 5000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 5000,
      },
      {
        id: 513,
        parent_id: 5,
        sub_type_name: 'indomaret',
        sub_type: 6,
        cat: 'digitalshoping',
        name: 'Voucher Saldo Indomaret',
        ammounts: 105000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 105000,
      },
      {
        id: 514,
        parent_id: 5,
        sub_type_name: 'alfamart',
        sub_type: 7,
        cat: 'digitalshoping',
        name: 'Voucher Saldo Alfamart',
        ammounts: 200000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 200000,
      },
      {
        id: 514,
        parent_id: 5,
        sub_type_name: 'alfamart',
        sub_type: 7,
        cat: 'digitalshoping',
        name: 'Voucher Saldo Alfamart',
        ammounts: 200000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 200000,
      },
      {
        id: 514,
        parent_id: 5,
        sub_type_name: 'alfamart',
        sub_type: 7,
        cat: 'digitalshoping',
        name: 'Voucher Saldo Alfamart',
        ammounts: 200000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 200000,
      },
      {
        id: 514,
        parent_id: 5,
        sub_type_name: 'alfamart',
        sub_type: 7,
        cat: 'digitalshoping',
        name: 'Voucher Saldo Alfamart',
        ammounts: 200000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 200000,
      },
      {
        id: 514,
        parent_id: 5,
        sub_type_name: 'alfamart',
        sub_type: 7,
        cat: 'digitalshoping',
        name: 'Voucher Saldo Alfamart',
        ammounts: 200000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 200000,
      },
      {
        id: 514,
        parent_id: 5,
        sub_type_name: 'alfamart',
        sub_type: 7,
        cat: 'digitalshoping',
        name: 'Voucher Saldo Alfamart',
        ammounts: 200000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 200000,
      },
      {
        id: 514,
        parent_id: 5,
        sub_type_name: 'alfamart',
        sub_type: 7,
        cat: 'digitalshoping',
        name: 'Voucher Saldo Alfamart',
        ammounts: 200000,
        img: '',
        terms: [
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
          'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        ],
        desc: 'Nam justo lorem, congue ac gravida eget, pharetra vel enim. Phasellus metus eros, commodo id nunc ut, hendrerit tempor enim. Suspendisse augue urna, imperdiet ac porttitor aliquet, dapibus ac eros',
        howto: [
          'Beli voucher dengan menekan tombol Redeem',
          'Morbi feugiat odio vel gravida laoreet. Nullam id arcu erat. Duis vulputate, odio non bibendum porta, magna orci porttitor tellus',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        ],
        active: 200000,
      },
    ],
  },
]

export const data_cat_tab_redeem = [
  { id: 1, name: 'Prestisa Reward' },
  { id: 2, name: 'Merchants' },
]

export const data_cat_tab_detail_redeem = [
  { id: 1, name: 'Info Voucher' },
  { id: 2, name: 'Syarat dan Ketentuan ' },
]

export const data_confirm_redeem_reward_success = {
  title: 'Yeay! Voucher sedang diproses',
  subtitle:
    'Jika belum diterima dalam waktu 1 Jam, kamu bisa hubungi Layanan Pelanggan',
  voucher_type: 'ovo',
  voucher_name: 'Voucher OVO  25.000',
  phone: '0811112345',
  order_id: '974730702',
  order_date: '2002-01-01',
}

/**
 *
 * field numnber:  jika e-wallet refer phone number, jika token listrik refer account listrik number
 */

export const data_my_vouchers = [
  {
    id: 8,
    type: 'digitalwallet',
    name: 'Dompet Digital',
    icon: '',
    child: [
      {
        id: 811,
        parent_id: 8,
        type_id: 1,
        type: 'ovo',
        order_date: '2022-01-02',
        order_id: '878798090',
        voucher_name: 'Voucher Saldo OVO',
        ammounts: 25000,
        active: 25000,
        account_number: '0865566556775',
        img: '',
        status_redeem: 'proses',
        status_name: 'Dalam Proses',
        status_id: 1,
      },
      {
        id: 812,
        parent_id: 8,
        type_id: 1,
        type: 'ovo',
        order_date: '2022-01-02',
        order_id: '878798090',
        voucher_name: 'Voucher Saldo OVO',
        ammounts: 100000,
        active: 100000,
        account_number: '086556654475',
        img: '',
        status_redeem: 'berhasil',
        status_name: 'Berhasil',
        status_id: 1,
      },
    ],
  },
  {
    id: 4,
    type: 'tokenlistrik',
    name: 'Token Listrik',
    icon: '',
    child: [
      {
        id: 411,
        parent_id: 4,
        type_id: 4,
        type: 'tokenlistrik',
        order_date: '2022-01-02',
        order_id: '878798090',
        voucher_name: 'Voucher Token Listrik PLN',
        ammounts: 100000,
        active: 100000,
        account_number: '786556654475',
        account_name: 'Sania Minyak',
        token_electric_code: '123128212938',
        img: '',
        status_redeem: 'berhasil',
        status_name: 'Berhasil',
        status_id: 1,
      },
    ],
  },
]
